spring:
  docker:
    compose:
      enabled: true
      file: development/docker/minio/compose.yaml
      lifecycle-management: start_only
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: photo
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
server:
  port: 6129