spring:
  application:
    name: shishki
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
server:
  port: ${SHISHKI_PORT:6128}
photo-service:
  url: ${PHOTO_SERVICE_URL:http://localhost:6129}
frontend:
  url: ${FRONTEND_URL:http://localhost:3000/}