spring:
  application:
    name: shishki
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${SHISHKI_PORT:6128}
photo-service:
  url: ${PHOTO_SERVICE_URL:http://localhost:6129}
frontend:
  url: ${FRONTEND_URL:http://localhost:3000/}